import type {
  AiAgent,
  AiEvent,
  AppUser,
  AuditEvent,
  BusinessRule,
  CalendarConfig,
  CommunicationTemplate,
  CompanyInfo,
  Customer,
  Faq,
  GeneralSettings,
  Integration,
  KbDocument,
  KnowledgeStatus,
  NotificationRule,
  PendingAction,
  PlanningConfig,
  Preleveur,
  PriorityRule,
  Sampling,
  SamplingRequest,
  SentMessage,
  SecuritySettings,
  SystemLog,
  Site,
} from "./qualiup-types";

export const LABS = ["Agadir", "Casablanca", "Safi", "Marrakech"];

export const ANALYSIS_TYPES = [
  "Analyse microbiologique",
  "Analyse physico-chimique",
  "Analyse eau potable",
  "Contrôle surfaces / hygiène",
  "Résidus de pesticides",
];

export const WEEK_DAYS = ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"];

export const TODAY = "24/09/2026";

export const customers: Customer[] = [
  {
    id: "c1",
    name: "ABC Food",
    contact: "Hassan Lamrani",
    phone: "+212 661 20 34 55",
    email: "h.lamrani@abcfood.ma",
    city: "Agadir",
    sector: "Agroalimentaire",
    active: true,
  },
  {
    id: "c2",
    name: "Atlas Lait",
    contact: "Fatima Zahra Cherkaoui",
    phone: "+212 662 88 14 02",
    email: "qualite@atlaslait.ma",
    city: "Casablanca",
    sector: "Produits laitiers",
    active: true,
  },
  {
    id: "c3",
    name: "Souss Marine",
    contact: "Omar Boukhriss",
    phone: "+212 663 45 71 19",
    email: "o.boukhriss@soussmarine.ma",
    city: "Agadir",
    sector: "Produits de la mer",
    active: true,
  },
  {
    id: "c4",
    name: "Maroc Conserve",
    contact: "Leila Fassi",
    phone: "+212 664 12 90 76",
    email: "l.fassi@marocconserve.ma",
    city: "Safi",
    sector: "Conserverie",
    active: true,
  },
  {
    id: "c5",
    name: "Hôtel Al Massira",
    contact: "Younes Tazi",
    phone: "+212 665 33 21 40",
    email: "hygiene@almassira.ma",
    city: "Agadir",
    sector: "Hôtellerie",
    active: true,
  },
  {
    id: "c6",
    name: "Bio Farm Souss",
    contact: "Karim El Idrissi",
    phone: "+212 667 74 55 88",
    email: "k.elidrissi@biofarmsouss.ma",
    city: "Taroudant",
    sector: "Production agricole",
    active: false,
  },
];

export const sites: Site[] = [
  { id: "s1", customerId: "c1", name: "Usine Agadir Zone Industrielle", address: "Lot 145, Z.I. Tassila", city: "Agadir", sector: "Agroalimentaire", lab: "Agadir" },
  { id: "s2", customerId: "c1", name: "Entrepôt Inezgane", address: "Route de Biougra km 4", city: "Inezgane", sector: "Logistique froid", lab: "Agadir" },
  { id: "s3", customerId: "c2", name: "Centrale laitière Aïn Sebaa", address: "12 rue des Oudayas", city: "Casablanca", sector: "Produits laitiers", lab: "Casablanca" },
  { id: "s4", customerId: "c3", name: "Atelier de transformation port", address: "Quai nord, Port d'Agadir", city: "Agadir", sector: "Produits de la mer", lab: "Agadir" },
  { id: "s5", customerId: "c4", name: "Conserverie Safi Sud", address: "Av. Mohammed V, Z.I. Sud", city: "Safi", sector: "Conserverie", lab: "Safi" },
  { id: "s6", customerId: "c5", name: "Cuisine centrale hôtel", address: "Bd du 20 Août", city: "Agadir", sector: "Restauration", lab: "Agadir" },
  { id: "s7", customerId: "c6", name: "Ferme Ouled Berhil", address: "Douar Ouled Berhil", city: "Taroudant", sector: "Agriculture", lab: "Agadir" },
];

export const preleveurs: Preleveur[] = [
  {
    id: "p1",
    name: "Ahmed Bennani",
    lab: "Agadir",
    skills: ["Prélèvement aseptique", "Chaîne du froid", "Audit hygiène"],
    analysisTypes: ["Analyse microbiologique", "Contrôle surfaces / hygiène", "Analyse eau potable"],
    hours: "08:00 — 17:00",
    maxDaily: 8,
    area: "Grand Agadir",
    active: true,
    availability: { Lundi: true, Mardi: true, Mercredi: true, Jeudi: true, Vendredi: true, Samedi: false },
  },
  {
    id: "p2",
    name: "Salma Aït Baha",
    lab: "Agadir",
    skills: ["Prélèvement eau", "Physico-chimie"],
    analysisTypes: ["Analyse eau potable", "Analyse physico-chimique"],
    hours: "08:30 — 16:30",
    maxDaily: 6,
    area: "Agadir / Taroudant",
    active: true,
    availability: { Lundi: true, Mardi: true, Mercredi: false, Jeudi: true, Vendredi: true, Samedi: true },
  },
  {
    id: "p3",
    name: "Khalid Idrissi",
    lab: "Casablanca",
    skills: ["Prélèvement aseptique", "Produits laitiers"],
    analysisTypes: ["Analyse microbiologique", "Analyse physico-chimique"],
    hours: "08:00 — 18:00",
    maxDaily: 8,
    area: "Grand Casablanca",
    active: true,
    availability: { Lundi: true, Mardi: true, Mercredi: true, Jeudi: true, Vendredi: true, Samedi: false },
  },
  {
    id: "p4",
    name: "Youssef Ouazzani",
    lab: "Safi",
    skills: ["Conserverie", "Résidus"],
    analysisTypes: ["Résidus de pesticides", "Analyse microbiologique"],
    hours: "08:00 — 17:00",
    maxDaily: 7,
    area: "Safi / El Jadida",
    active: true,
    availability: { Lundi: true, Mardi: false, Mercredi: true, Jeudi: true, Vendredi: true, Samedi: false },
  },
  {
    id: "p5",
    name: "Nadia Bouzid",
    lab: "Marrakech",
    skills: ["Contrôle surfaces", "Restauration collective"],
    analysisTypes: ["Contrôle surfaces / hygiène", "Analyse eau potable"],
    hours: "09:00 — 17:00",
    maxDaily: 6,
    area: "Marrakech / Essaouira",
    active: false,
    availability: { Lundi: true, Mardi: true, Mercredi: true, Jeudi: false, Vendredi: true, Samedi: false },
  },
];

export const requests: SamplingRequest[] = [
  {
    id: "r245",
    ref: "#245",
    receivedAt: "24/09/2026 10:42",
    customerId: "c1",
    siteId: "s1",
    lab: "Agadir",
    analysisType: "Analyse microbiologique",
    samples: 8,
    urgency: "normale",
    requestedDate: "25/09/2026",
    requestedTime: "Matin",
    source: "WhatsApp",
    status: "à valider",
    confidence: 94,
    notes: "Accès par le portail logistique. Demander le responsable qualité sur site.",
    originalMessage: "Bonjour, nous avons besoin d’un prélèvement microbiologique demain matin à notre usine de Tassila. Il y aura 8 échantillons. Merci de nous proposer un créneau.",
    extraction: [
      { label: "Client", value: "ABC Food", confidence: 98 },
      { label: "Site", value: "Usine Agadir Zone Industrielle", confidence: 94 },
      { label: "Adresse", value: "Lot 145, Z.I. Tassila", confidence: 91 },
      { label: "Type d'analyse", value: "Analyse microbiologique", confidence: 96 },
      { label: "Échantillons", value: "8", confidence: 99 },
      { label: "Urgence", value: "Normale", confidence: 89 },
    ],
    recommendation: {
      date: "25/09/2026",
      slot: "09:30 — 11:00",
      preleveurId: "p1",
      lab: "Agadir",
      reason: "Disponibilité du préleveur + proximité avec une autre opération prévue à Tassila.",
    },
  },
  {
    id: "r246",
    ref: "#246",
    receivedAt: "24/09/2026 09:15",
    customerId: "c3",
    siteId: "s4",
    lab: "Agadir",
    analysisType: "Contrôle surfaces / hygiène",
    samples: 14,
    urgency: "élevée",
    requestedDate: "24/09/2026",
    requestedTime: "14:00",
    source: "WhatsApp",
    status: "à valider",
    confidence: 82,
    notes: "Contrôle demandé après non-conformité interne.",
    originalMessage: "Bonjour QualiUp, contrôle urgent des surfaces aujourd’hui à notre atelier du port. Nous avons 14 points à prélever, idéalement vers 14h.",
    extraction: [
      { label: "Client", value: "Souss Marine", confidence: 96 },
      { label: "Site", value: "Atelier de transformation port", confidence: 88 },
      { label: "Type d'analyse", value: "Contrôle surfaces / hygiène", confidence: 84 },
      { label: "Échantillons", value: "14", confidence: 95 },
      { label: "Urgence", value: "Élevée", confidence: 92 },
      { label: "Créneau souhaité", value: "14:00", confidence: 71 },
    ],
    recommendation: {
      date: "24/09/2026",
      slot: "14:30 — 16:00",
      preleveurId: "p1",
      lab: "Agadir",
      reason: "Urgence élevée : seul créneau compatible avec la capacité restante du préleveur.",
    },
  },
  {
    id: "r247",
    ref: "#247",
    receivedAt: "24/09/2026 08:55",
    customerId: "c2",
    siteId: "s3",
    lab: "Casablanca",
    analysisType: "Analyse physico-chimique",
    samples: 6,
    urgency: "normale",
    requestedDate: "26/09/2026",
    requestedTime: "Matin",
    source: "Email",
    status: "planifiée",
    confidence: 97,
    notes: "Contrôle mensuel contractuel.",
    extraction: [
      { label: "Client", value: "Atlas Lait", confidence: 99 },
      { label: "Site", value: "Centrale laitière Aïn Sebaa", confidence: 97 },
      { label: "Type d'analyse", value: "Analyse physico-chimique", confidence: 98 },
      { label: "Échantillons", value: "6", confidence: 99 },
      { label: "Urgence", value: "Normale", confidence: 93 },
    ],
    recommendation: {
      date: "26/09/2026",
      slot: "08:30 — 09:30",
      preleveurId: "p3",
      lab: "Casablanca",
      reason: "Contrat récurrent : créneau habituel du client conservé.",
    },
  },
  {
    id: "r248",
    ref: "#248",
    receivedAt: "23/09/2026 16:40",
    customerId: "c4",
    siteId: "s5",
    lab: "Safi",
    analysisType: "Résidus de pesticides",
    samples: 24,
    urgency: "critique",
    requestedDate: "25/09/2026",
    requestedTime: "08:00",
    source: "WhatsApp",
    status: "à valider",
    confidence: 76,
    notes: "Volume important : validation humaine obligatoire (> 20 échantillons).",
    extraction: [
      { label: "Client", value: "Maroc Conserve", confidence: 93 },
      { label: "Site", value: "Conserverie Safi Sud", confidence: 90 },
      { label: "Type d'analyse", value: "Résidus de pesticides", confidence: 79 },
      { label: "Échantillons", value: "24", confidence: 97 },
      { label: "Urgence", value: "Critique", confidence: 88 },
      { label: "Instructions", value: "Lot export UE", confidence: 64 },
    ],
    recommendation: {
      date: "25/09/2026",
      slot: "08:00 — 11:00",
      preleveurId: "p4",
      lab: "Safi",
      reason: "Volume élevé : créneau long réservé, regroupement avec l'opération Safi du matin.",
    },
  },
  {
    id: "r249",
    ref: "#249",
    receivedAt: "23/09/2026 14:05",
    customerId: "c5",
    siteId: "s6",
    lab: "Agadir",
    analysisType: "Analyse eau potable",
    samples: 4,
    urgency: "basse",
    requestedDate: "28/09/2026",
    requestedTime: "Matin",
    source: "WhatsApp",
    status: "validée",
    confidence: 91,
    notes: "Contrôle trimestriel de la cuisine centrale.",
    extraction: [
      { label: "Client", value: "Hôtel Al Massira", confidence: 95 },
      { label: "Site", value: "Cuisine centrale hôtel", confidence: 92 },
      { label: "Type d'analyse", value: "Analyse eau potable", confidence: 94 },
      { label: "Échantillons", value: "4", confidence: 98 },
      { label: "Urgence", value: "Basse", confidence: 85 },
    ],
    recommendation: {
      date: "28/09/2026",
      slot: "10:00 — 11:00",
      preleveurId: "p2",
      lab: "Agadir",
      reason: "Faible urgence : créneau creux du lundi utilisé pour lisser la charge.",
    },
  },
  {
    id: "r250",
    ref: "#250",
    receivedAt: "23/09/2026 11:20",
    customerId: "c6",
    siteId: "s7",
    lab: "Agadir",
    analysisType: "Résidus de pesticides",
    samples: 10,
    urgency: "normale",
    requestedDate: "27/09/2026",
    requestedTime: "Non précisé",
    source: "WhatsApp",
    status: "clarification",
    confidence: 58,
    notes: "Informations manquantes : parcelle et date exacte non identifiées.",
    extraction: [
      { label: "Client", value: "Bio Farm Souss", confidence: 88 },
      { label: "Site", value: "Ferme Ouled Berhil", confidence: 61 },
      { label: "Type d'analyse", value: "Résidus de pesticides", confidence: 72 },
      { label: "Échantillons", value: "10", confidence: 66 },
      { label: "Date souhaitée", value: "Non précisée", confidence: 31 },
    ],
    recommendation: {
      date: "27/09/2026",
      slot: "À confirmer",
      preleveurId: "p2",
      lab: "Agadir",
      reason: "Confiance sous le seuil : demande de clarification envoyée avant planification.",
    },
  },
  {
    id: "r251",
    ref: "#251",
    receivedAt: "22/09/2026 17:32",
    customerId: "c1",
    siteId: "s2",
    lab: "Agadir",
    analysisType: "Analyse microbiologique",
    samples: 5,
    urgency: "normale",
    requestedDate: "24/09/2026",
    requestedTime: "Après-midi",
    source: "API",
    status: "planifiée",
    confidence: 96,
    notes: "Créée automatiquement depuis le système QualiUp.",
    extraction: [
      { label: "Client", value: "ABC Food", confidence: 99 },
      { label: "Site", value: "Entrepôt Inezgane", confidence: 96 },
      { label: "Type d'analyse", value: "Analyse microbiologique", confidence: 97 },
      { label: "Échantillons", value: "5", confidence: 99 },
    ],
    recommendation: {
      date: "24/09/2026",
      slot: "15:00 — 16:00",
      preleveurId: "p1",
      lab: "Agadir",
      reason: "Regroupement avec l'opération ABC Food du matin (même client, même axe).",
    },
  },
];

export const samplings: Sampling[] = [
  { id: "o1", ref: "PRL-2601", requestRef: "#251", customerId: "c1", siteId: "s2", date: "24/09/2026", slot: "15:00 — 16:00", preleveurId: "p1", analysisType: "Analyse microbiologique", samples: 5, status: "planifié", price: 2400, lab: "Agadir" },
  { id: "o2", ref: "PRL-2598", requestRef: "#243", customerId: "c3", siteId: "s4", date: "24/09/2026", slot: "09:00 — 10:30", preleveurId: "p1", analysisType: "Contrôle surfaces / hygiène", samples: 12, status: "en cours", price: 3100, lab: "Agadir" },
  { id: "o3", ref: "PRL-2597", customerId: "c5", requestRef: "#241", siteId: "s6", date: "24/09/2026", slot: "08:00 — 09:00", preleveurId: "p2", analysisType: "Analyse eau potable", samples: 4, status: "réalisé", price: 1600, lab: "Agadir" },
  { id: "o4", ref: "PRL-2596", requestRef: "#240", customerId: "c2", siteId: "s3", date: "24/09/2026", slot: "08:30 — 10:00", preleveurId: "p3", analysisType: "Analyse physico-chimique", samples: 6, status: "réalisé", price: 2750, lab: "Casablanca" },
  { id: "o5", ref: "PRL-2594", requestRef: "#238", customerId: "c4", siteId: "s5", date: "23/09/2026", slot: "14:00 — 16:00", preleveurId: "p4", analysisType: "Résidus de pesticides", samples: 18, status: "en retard", price: 6800, lab: "Safi" },
  { id: "o6", ref: "PRL-2602", requestRef: "#247", customerId: "c2", siteId: "s3", date: "26/09/2026", slot: "08:30 — 09:30", preleveurId: "p3", analysisType: "Analyse physico-chimique", samples: 6, status: "planifié", price: 2750, lab: "Casablanca" },
  { id: "o7", ref: "PRL-2603", requestRef: "#249", customerId: "c5", siteId: "s6", date: "28/09/2026", slot: "10:00 — 11:00", preleveurId: "p2", analysisType: "Analyse eau potable", samples: 4, status: "planifié", price: 1600, lab: "Agadir" },
  { id: "o8", ref: "PRL-2590", requestRef: "#235", customerId: "c1", siteId: "s1", date: "22/09/2026", slot: "09:30 — 11:00", preleveurId: "p1", analysisType: "Analyse microbiologique", samples: 8, status: "réalisé", price: 3400, lab: "Agadir" },
  { id: "o9", ref: "PRL-2591", requestRef: "#236", customerId: "c3", siteId: "s4", date: "22/09/2026", slot: "13:00 — 14:00", preleveurId: "p2", analysisType: "Analyse eau potable", samples: 3, status: "annulé", price: 0, lab: "Agadir" },
];

export const agents: AiAgent[] = [
  {
    id: "a1",
    name: "Agent Prélèvements",
    description:
      "Détecte les demandes de prélèvement, extrait les données structurées et propose une planification optimisée.",
    active: true,
    hours: "07:00 — 21:00",
    autoThreshold: 90,
    validateThreshold: 70,
    detectionRules:
      "Une demande de prélèvement est détectée lorsqu'un client exprime un besoin d'analyse avec au moins un site identifiable et une intention de date.",
    fields: [
      { label: "Client", required: true },
      { label: "Site", required: true },
      { label: "Adresse", required: true },
      { label: "Ville", required: true },
      { label: "Secteur", required: false },
      { label: "Type d'analyse", required: true },
      { label: "Nombre d'échantillons", required: true },
      { label: "Urgence", required: true },
      { label: "Date souhaitée", required: true },
      { label: "Créneau souhaité", required: false },
      { label: "Instructions particulières", required: false },
    ],
    permissions: [
      { action: "Lire les demandes", level: "autorisé" },
      { action: "Créer une proposition", level: "autorisé" },
      { action: "Modifier le planning", level: "validation" },
      { action: "Affecter un préleveur", level: "validation" },
      { action: "Annuler une opération", level: "interdit" },
    ],
    actionsToday: 34,
    successRate: 96,
  },
  {
    id: "a2",
    name: "Agent Communication Client",
    description:
      "Envoie confirmations, rappels et notifications de résultats selon les modèles validés.",
    active: true,
    hours: "07:00 — 20:00",
    autoThreshold: 92,
    validateThreshold: 75,
    detectionRules:
      "Déclenché par les événements opérationnels : planification confirmée, veille d'intervention, prélèvement réalisé, résultats disponibles.",
    fields: [
      { label: "Client", required: true },
      { label: "Site", required: true },
      { label: "Date", required: true },
      { label: "Créneau", required: true },
      { label: "Préleveur", required: false },
    ],
    permissions: [
      { action: "Envoyer une confirmation", level: "autorisé" },
      { action: "Envoyer un rappel", level: "autorisé" },
      { action: "Reporter un rendez-vous", level: "validation" },
      { action: "Annuler un rendez-vous", level: "validation" },
      { action: "Notifier les résultats", level: "autorisé" },
    ],
    actionsToday: 51,
    successRate: 99,
    comms: {
      confirmationEnabled: true,
      confirmationTiming: "Immédiatement après validation",
      reminderDayBefore: true,
      reminderSameDay: true,
      reminderTiming: "18:00 la veille / 2 h avant",
      reschedulePolicy: "validation",
      cancellationAllowed: true,
      cancellationNeedsApproval: true,
      resultsNotification: true,
    },
  },
  {
    id: "a3",
    name: "Agent Service Client",
    description:
      "Répond aux questions courantes à partir de la base de connaissances (FAQ, documents, informations générales).",
    active: true,
    hours: "24/7",
    autoThreshold: 88,
    validateThreshold: 65,
    detectionRules:
      "Question informative sans intention opérationnelle : délais, tarifs, accréditations, modalités de prélèvement.",
    fields: [
      { label: "Sujet de la question", required: true },
      { label: "Client identifié", required: false },
    ],
    permissions: [
      { action: "Consulter la base de connaissances", level: "autorisé" },
      { action: "Répondre au client", level: "autorisé" },
      { action: "Transmettre un document", level: "autorisé" },
      { action: "Communiquer un tarif", level: "validation" },
      { action: "Engager QualiUp contractuellement", level: "interdit" },
    ],
    actionsToday: 22,
    successRate: 93,
  },
];

export const pendingActions: PendingAction[] = [
  {
    id: "act1",
    category: "Planning",
    agentId: "a1",
    title: "Planifier la demande #245 — ABC Food",
    proposal: ["Date : 25/09/2026", "Créneau : 09:30 — 11:00", "Préleveur : Ahmed Bennani", "Laboratoire : Agadir"],
    reason: "Disponibilité du préleveur + proximité avec une autre opération prévue à Tassila.",
    confidence: 94,
    impact: "moyen",
    createdAt: "24/09/2026 10:43",
    status: "en attente",
    requestRef: "#245",
  },
  {
    id: "act2",
    category: "Affectation préleveur",
    agentId: "a1",
    title: "Affecter Ahmed Bennani à la demande urgente #246",
    proposal: ["Date : 24/09/2026", "Créneau : 14:30 — 16:00", "Préleveur : Ahmed Bennani", "Charge du jour : 4 / 8"],
    reason: "Urgence élevée : seul préleveur habilité au contrôle de surfaces disponible aujourd'hui.",
    confidence: 82,
    impact: "élevé",
    createdAt: "24/09/2026 09:18",
    status: "en attente",
    requestRef: "#246",
  },
  {
    id: "act3",
    category: "Planning",
    agentId: "a1",
    title: "Créneau long pour la demande #248 — Maroc Conserve",
    proposal: ["Date : 25/09/2026", "Créneau : 08:00 — 11:00", "Préleveur : Youssef Ouazzani", "24 échantillons"],
    reason: "Règle métier : plus de 20 échantillons impose une validation humaine.",
    confidence: 76,
    impact: "élevé",
    createdAt: "23/09/2026 16:44",
    status: "en attente",
    requestRef: "#248",
  },
  {
    id: "act4",
    category: "Modification de rendez-vous",
    agentId: "a2",
    title: "Reporter l'opération PRL-2594 — Maroc Conserve",
    proposal: ["Ancien créneau : 23/09 14:00", "Nouveau créneau : 25/09 14:00", "Motif : préleveur indisponible"],
    reason: "Opération en retard : report proposé sur le premier créneau compatible.",
    confidence: 88,
    impact: "moyen",
    createdAt: "24/09/2026 08:10",
    status: "en attente",
  },
  {
    id: "act5",
    category: "Communication client",
    agentId: "a2",
    title: "Informer Bio Farm Souss d'une information manquante",
    proposal: ["Modèle : Demande de clarification", "Canal : WhatsApp", "Champs manquants : parcelle, date"],
    reason: "Confiance d'extraction 58 % : sous le seuil de traitement automatique.",
    confidence: 58,
    impact: "faible",
    createdAt: "23/09/2026 11:25",
    status: "en attente",
    requestRef: "#250",
  },
  {
    id: "act6",
    category: "Annulation",
    agentId: "a2",
    title: "Annuler l'opération PRL-2591 — Souss Marine",
    proposal: ["Opération : PRL-2591", "Date : 22/09/2026", "Motif client : site fermé"],
    reason: "Demande d'annulation reçue du client, action sensible soumise à validation.",
    confidence: 91,
    impact: "moyen",
    createdAt: "22/09/2026 09:02",
    status: "approuvée",
    decidedBy: "Khaoula",
  },
];

export const businessRules: BusinessRule[] = [
  { id: "br1", name: "Urgence élevée prioritaire", condition: "urgence = élevée ou critique", action: "priorité = maximale", active: true, scope: "Planification" },
  { id: "br2", name: "Gros volume à valider", condition: "nombre d'échantillons > 20", action: "validation humaine = obligatoire", active: true, scope: "Validation" },
  { id: "br3", name: "Longue distance à valider", condition: "distance > 100 km", action: "validation humaine = obligatoire", active: true, scope: "Validation" },
  { id: "br4", name: "Regroupement même site", condition: "prélèvements sur le même site le même jour", action: "regrouper dans un seul créneau", active: true, scope: "Optimisation" },
  { id: "br5", name: "Préleveur indisponible", condition: "préleveur indisponible", action: "chercher une alternative dans le même laboratoire", active: true, scope: "Planification" },
  { id: "br6", name: "Confiance faible", condition: "confiance IA < 70 %", action: "demander une clarification au client", active: true, scope: "IA" },
  { id: "br7", name: "Client inactif", condition: "client inactif ou en litige", action: "bloquer la planification automatique", active: false, scope: "Commercial" },
];

export const priorityRules: PriorityRule[] = [
  { id: "pr1", label: "Urgence de la demande", active: true },
  { id: "pr2", label: "Disponibilité du préleveur", active: true },
  { id: "pr3", label: "Proximité géographique", active: true },
  { id: "pr4", label: "Regroupement des sites", active: true },
  { id: "pr5", label: "Optimisation du temps de trajet", active: true },
  { id: "pr6", label: "Spécialisation du laboratoire", active: true },
  { id: "pr7", label: "Échéance contractuelle la plus proche", active: false },
];

export const faqs: Faq[] = [
  { id: "f1", question: "Quel est le délai de rendu des résultats ?", answer: "Les résultats microbiologiques sont disponibles en 3 à 5 jours ouvrés, les analyses physico-chimiques en 5 à 7 jours ouvrés.", category: "Délais", active: true, priority: 1 },
  { id: "f2", question: "Comment préparer un prélèvement d'eau potable ?", answer: "Laissez couler l'eau 2 minutes, ne désinfectez pas le robinet avant le passage du préleveur et gardez l'accès au point de puisage dégagé.", category: "Prélèvement", active: true, priority: 2 },
  { id: "f3", question: "QualiUp est-il accrédité ?", answer: "Oui, QualiUp opère selon la norme ISO/IEC 17025 pour les analyses microbiologiques et physico-chimiques.", category: "Accréditation", active: true, priority: 1 },
  { id: "f4", question: "Puis-je modifier la date d'un prélèvement ?", answer: "Oui, jusqu'à 24 h avant l'intervention. Toute modification est confirmée par notre équipe.", category: "Planning", active: true, priority: 3 },
  { id: "f5", question: "Quels sont vos tarifs ?", answer: "Les tarifs dépendent du type d'analyse et du nombre d'échantillons. Un devis est transmis par l'équipe commerciale.", category: "Tarifs", active: false, priority: 4 },
];

export const kbDocuments: KbDocument[] = [
  { id: "d1", name: "Guide de prélèvement microbiologique.pdf", category: "Procédures", size: "1,8 Mo", visibility: "client", keywords: "prélèvement, microbiologie, aseptique", updatedAt: "12/09/2026", indexed: true },
  { id: "d2", name: "Certificat ISO 17025.pdf", category: "Accréditation", size: "640 Ko", visibility: "public", keywords: "iso, accréditation, 17025", updatedAt: "02/07/2026", indexed: true },
  { id: "d3", name: "Grille tarifaire 2026.xlsx", category: "Commercial", size: "220 Ko", visibility: "interne", keywords: "tarif, prix, devis", updatedAt: "18/09/2026", indexed: true },
  { id: "d4", name: "Conditions générales de service.pdf", category: "Juridique", size: "410 Ko", visibility: "client", keywords: "cgv, contrat, conditions", updatedAt: "05/05/2026", indexed: false },
  { id: "d5", name: "Fiche chaîne du froid.pdf", category: "Procédures", size: "780 Ko", visibility: "client", keywords: "froid, transport, température", updatedAt: "21/09/2026", indexed: true },
];

export const templates: CommunicationTemplate[] = [
  { id: "t1", name: "Confirmation de prélèvement", trigger: "Planification validée", channel: "WhatsApp", body: "Bonjour {contact}, votre prélèvement est confirmé le {date} entre {creneau} sur le site {site}. Préleveur : {preleveur}. — QualiUp", active: true, approvalMode: "automatique" },
  { id: "t2", name: "Rappel de prélèvement", trigger: "Veille à 18:00", channel: "WhatsApp", body: "Rappel : intervention QualiUp demain {date} à {creneau} sur {site}. Merci de préparer l'accès aux points de prélèvement.", active: true, approvalMode: "automatique" },
  { id: "t3", name: "Préleveur en route", trigger: "Départ du préleveur", channel: "WhatsApp", body: "Votre préleveur {preleveur} est en route vers {site}. Arrivée estimée : {heure}.", active: true, approvalMode: "automatique" },
  { id: "t4", name: "Demande de clarification", trigger: "Demande incomplète", channel: "WhatsApp", body: "Bonjour, afin de planifier votre prélèvement, pourriez-vous préciser : {champs_manquants} ?", active: true, approvalMode: "validation humaine" },
  { id: "t5", name: "Prélèvement effectué", trigger: "Opération réalisée", channel: "WhatsApp", body: "Le prélèvement sur {site} a été réalisé le {date}. {echantillons} échantillons ont été acheminés au laboratoire de {laboratoire}.", active: true, approvalMode: "automatique" },
  { id: "t6", name: "Résultats disponibles", trigger: "Résultats publiés", channel: "WhatsApp", body: "Bonjour {contact}, les résultats de l'opération {operation} sont disponibles sur votre espace QualiUp.", active: true, approvalMode: "validation humaine" },
];

export const sentMessages: SentMessage[] = [
  { id: "m1", sentAt: "24/09/2026 10:51", customer: "Atlas Lait", requestRef: "#247", template: "Confirmation de prélèvement", channel: "WhatsApp", status: "envoyé" },
  { id: "m2", sentAt: "24/09/2026 08:30", customer: "ABC Food", requestRef: "#241", template: "Rappel de prélèvement", channel: "WhatsApp", status: "envoyé" },
  { id: "m3", sentAt: "24/09/2026 08:30", customer: "Hôtel Al Massira", requestRef: "#239", template: "Rappel de prélèvement", channel: "WhatsApp", status: "envoyé" },
  { id: "m4", sentAt: "23/09/2026 16:12", customer: "Souss Marine", requestRef: "#238", template: "Prélèvement effectué", channel: "WhatsApp", status: "envoyé" },
  { id: "m5", sentAt: "23/09/2026 11:25", customer: "Bio Farm Souss", requestRef: "#250", template: "Demande de clarification", channel: "WhatsApp", status: "à valider" },
];

export const integrations: Integration[] = [
  {
    id: "i1",
    name: "WhatsApp Business",
    category: "Canal client",
    status: "connecté",
    lastEvent: "24/09/2026 10:43",
    lastSync: "24/09/2026 10:43",
    errors: 0,
    webhookActive: true,
    details: [
      { label: "Numéro configuré", value: "+212 528 84 12 00" },
      { label: "Identifiant WABA", value: "wa-qualiup-prod-01" },
      { label: "Webhook", value: "https://api.qualiup.ma/hooks/whatsapp" },
      { label: "Jeton d'accès", value: "••••••••••••7f2a", masked: true },
    ],
  },
  {
    id: "i2",
    name: "Calendrier",
    category: "Planification",
    status: "connecté",
    lastEvent: "24/09/2026 10:15",
    lastSync: "24/09/2026 10:15",
    errors: 0,
    webhookActive: true,
    details: [
      { label: "Fournisseur", value: "Google Calendar" },
      { label: "Calendrier", value: "QualiUp — Prélèvements" },
      { label: "Fréquence de synchronisation", value: "Toutes les 5 minutes" },
      { label: "Clé de service", value: "••••••••••••a91c", masked: true },
    ],
  },
  {
    id: "i3",
    name: "Système QualiUp",
    category: "Métier",
    status: "dégradé",
    lastEvent: "24/09/2026 09:58",
    lastSync: "24/09/2026 09:58",
    errors: 3,
    webhookActive: true,
    details: [
      { label: "URL de base", value: "https://erp.qualiup.ma/api/v2" },
      { label: "Authentification", value: "OAuth 2.0 (client credentials)" },
      { label: "Compte de service", value: "svc-backoffice@qualiup.ma" },
      { label: "Secret client", value: "••••••••••••3d55", masked: true },
    ],
  },
  {
    id: "i4",
    name: "Email transactionnel",
    category: "Canal client",
    status: "connecté",
    lastEvent: "24/09/2026 10:02",
    lastSync: "24/09/2026 10:02",
    errors: 0,
    webhookActive: false,
    details: [
      { label: "Expéditeur", value: "no-reply@qualiup.ma" },
      { label: "Domaine vérifié", value: "qualiup.ma (SPF + DKIM)" },
      { label: "Clé API", value: "••••••••••••b0e7", masked: true },
    ],
  },
  {
    id: "i5",
    name: "API publique",
    category: "Technique",
    status: "connecté",
    lastEvent: "24/09/2026 07:30",
    lastSync: "24/09/2026 07:30",
    errors: 1,
    webhookActive: true,
    details: [
      { label: "Point d'entrée", value: "https://api.qualiup.ma/backoffice/v1" },
      { label: "Clés actives", value: "2" },
      { label: "Limite de débit", value: "120 req/min" },
      { label: "Clé principale", value: "••••••••••••c412", masked: true },
    ],
  },
];

export const aiEvents: AiEvent[] = [
  { id: "e1", time: "10:42", date: TODAY, agentId: "a1", title: "Demande #245 détectée", fields: { Client: "ABC Food", Action: "Création d'une proposition", Confiance: "94 %" }, status: "validation requise" },
  { id: "e2", time: "10:51", date: TODAY, agentId: "a2", title: "Confirmation envoyée", fields: { Demande: "#247", Modèle: "Confirmation de prélèvement", Canal: "WhatsApp" }, status: "succès" },
  { id: "e3", time: "09:18", date: TODAY, agentId: "a1", title: "Demande #246 détectée — urgence élevée", fields: { Client: "Souss Marine", Action: "Affectation préleveur proposée", Confiance: "82 %" }, status: "validation requise" },
  { id: "e4", time: "09:58", date: TODAY, agentId: "a1", title: "Échec de synchronisation système QualiUp", fields: { Workflow: "sync-operations", Erreur: "HTTP 504 — délai dépassé" }, status: "erreur" },
  { id: "e5", time: "08:30", date: TODAY, agentId: "a2", title: "Rappels de la veille envoyés", fields: { Volume: "6 messages", Canal: "WhatsApp" }, status: "succès" },
  { id: "e6", time: "08:05", date: TODAY, agentId: "a3", title: "Question client traitée — délais de résultats", fields: { Source: "FAQ #1", Confiance: "96 %" }, status: "succès" },
  { id: "e7", time: "16:44", date: "23/09/2026", agentId: "a1", title: "Demande #248 détectée — volume élevé", fields: { Client: "Maroc Conserve", Règle: "Échantillons > 20", Confiance: "76 %" }, status: "validation requise" },
  { id: "e8", time: "11:25", date: "23/09/2026", agentId: "a3", title: "Clarification demandée", fields: { Demande: "#250", Motif: "Confiance 58 %" }, status: "refusé" },
];

export const systemLogs: SystemLog[] = [
  { id: "l1", timestamp: "24/09/2026 10:42:18", agent: "Agent Prélèvements", workflow: "detect-request", event: "Extraction structurée terminée", status: "succès", duration: "1,4 s" },
  { id: "l2", timestamp: "24/09/2026 10:42:59", agent: "Agent Prélèvements", workflow: "propose-schedule", event: "Proposition créée (#245)", status: "succès", duration: "2,1 s" },
  { id: "l3", timestamp: "24/09/2026 09:58:02", agent: "Système", workflow: "sync-operations", event: "Appel ERP QualiUp", status: "erreur", duration: "30,0 s", error: "HTTP 504 — Gateway timeout" },
  { id: "l4", timestamp: "24/09/2026 09:18:44", agent: "Agent Prélèvements", workflow: "assign-preleveur", event: "Recherche de créneau urgent", status: "avertissement", duration: "3,8 s", error: "Capacité préleveur proche du maximum" },
  { id: "l5", timestamp: "24/09/2026 08:30:11", agent: "Agent Communication", workflow: "send-reminders", event: "6 rappels envoyés", status: "succès", duration: "4,6 s" },
  { id: "l6", timestamp: "24/09/2026 07:30:00", agent: "Système", workflow: "calendar-sync", event: "Synchronisation calendrier", status: "succès", duration: "0,9 s" },
];

export const auditEvents: AuditEvent[] = [
  { id: "au1", user: "Khaoula", date: "23/09/2026 17:12", action: "Modification règle de planification", object: "Maximum prélèvements/jour", before: "7", after: "8" },
  { id: "au2", user: "Khaoula", date: "23/09/2026 16:50", action: "Validation d'action IA", object: "Annulation PRL-2591", before: "en attente", after: "approuvée" },
  { id: "au3", user: "Rachid", date: "22/09/2026 14:02", action: "Modification permission agent", object: "Agent Prélèvements — Annuler", before: "validation", after: "interdit" },
  { id: "au4", user: "Salma", date: "21/09/2026 10:31", action: "Activation modèle de message", object: "Résultats disponibles", before: "inactif", after: "actif" },
];

export const appUsers: AppUser[] = [
  { id: "u1", name: "Khaoula Benali", email: "k.benali@qualiup.ma", role: "Administrateur", active: true, lastLogin: "24/09/2026 08:02" },
  { id: "u2", name: "Rachid El Amrani", email: "r.elamrani@qualiup.ma", role: "Responsable opérations", active: true, lastLogin: "24/09/2026 07:48" },
  { id: "u3", name: "Salma Haddad", email: "s.haddad@qualiup.ma", role: "Service client", active: true, lastLogin: "23/09/2026 17:20" },
  { id: "u4", name: "Mehdi Chraibi", email: "m.chraibi@qualiup.ma", role: "Direction", active: true, lastLogin: "22/09/2026 19:05" },
  { id: "u5", name: "Imane Sabri", email: "i.sabri@qualiup.ma", role: "Technique", active: true, lastLogin: "24/09/2026 09:33" },
  { id: "u6", name: "Yassine Oubella", email: "y.oubella@qualiup.ma", role: "Responsable opérations", active: false, lastLogin: "02/08/2026 11:14" },
];

export const notificationRules: NotificationRule[] = [
  { id: "n1", label: "Actions IA à valider", recipients: "Responsable opérations, Administrateur", email: true, inApp: true },
  { id: "n2", label: "Erreurs d'intégration", recipients: "Technique", email: true, inApp: true },
  { id: "n3", label: "Conflits de planning", recipients: "Responsable opérations", email: false, inApp: true },
  { id: "n4", label: "Erreurs des agents IA", recipients: "Technique, Administrateur", email: true, inApp: true },
  { id: "n5", label: "Rapport quotidien d'activité", recipients: "Direction", email: true, inApp: false },
];

export const planningConfig: PlanningConfig = {
  workStart: "08:00",
  workEnd: "18:00",
  workDays: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
  durations: [30, 60, 90],
  defaultDuration: 60,
  buffer: 15,
  travelBuffer: 30,
  maxDaily: 8,
  holidays: "01/01, 11/01, 01/05, 30/07, 14/08, 20/08, 21/08, 06/11, 18/11",
};

export const calendarConfig: CalendarConfig = {
  provider: "Google Calendar",
  calendarName: "QualiUp — Prélèvements",
  syncFrequency: "Toutes les 5 minutes",
  conflictBehavior: "Le back-office est prioritaire",
  lastTest: "24/09/2026 10:15 — succès",
};

export const generalSettings: GeneralSettings = {
  company: "QualiUp",
  timezone: "Africa/Casablanca (GMT+1)",
  language: "Français",
  labs: LABS,
};

export const securitySettings: SecuritySettings = {
  sessionTimeout: 30,
  passwordMinLength: 12,
  mfa: true,
  ipRestriction: false,
  auditRetention: 24,
};

export const companyInfo: CompanyInfo = {
  name: "QualiUp",
  phone: "+212 528 84 12 00",
  email: "contact@qualiup.ma",
  website: "https://qualiup.com",
  social: "LinkedIn : /company/qualiup",
  hours: "Lundi — Vendredi, 08:00 — 18:00 · Samedi, 08:00 — 12:00",
  labs: "Agadir (siège), Casablanca, Safi, Marrakech",
};

export const knowledgeStatus: KnowledgeStatus = {
  lastSync: "21/09/2026 16:40",
  indexedChunks: 428,
  status: "désynchronisée",
};

export const revenueByDay = [
  { day: "18/09", ca: 14200, operations: 9 },
  { day: "19/09", ca: 11800, operations: 7 },
  { day: "20/09", ca: 9400, operations: 6 },
  { day: "21/09", ca: 16100, operations: 11 },
  { day: "22/09", ca: 18600, operations: 12 },
  { day: "23/09", ca: 15300, operations: 10 },
  { day: "24/09", ca: 12750, operations: 8 },
];

export const automationTrend = [
  { week: "S34", automatisation: 61, validation: 39 },
  { week: "S35", automatisation: 66, validation: 34 },
  { week: "S36", automatisation: 69, validation: 31 },
  { week: "S37", automatisation: 73, validation: 27 },
  { week: "S38", automatisation: 78, validation: 22 },
  { week: "S39", automatisation: 81, validation: 19 },
];

export const revenueByLab = [
  { lab: "Agadir", ca: 248000 },
  { lab: "Casablanca", ca: 196500 },
  { lab: "Safi", ca: 124300 },
  { lab: "Marrakech", ca: 78900 },
];

export const revenueByService = [
  { service: "Microbiologie", ca: 284000 },
  { service: "Physico-chimie", ca: 172400 },
  { service: "Eau potable", ca: 98200 },
  { service: "Surfaces / hygiène", ca: 64300 },
  { service: "Résidus", ca: 28800 },
];
