/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnaissancesRouteImport } from './routes/connaissances'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as DemandesIndexRouteImport } from './routes/demandes.index'
import { Route as DemandesIdRouteImport } from './routes/demandes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnaissancesRoute = ConnaissancesRouteImport.update({
  id: '/connaissances',
  path: '/connaissances',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIndexRoute = DemandesIndexRouteImport.update({
  id: '/demandes/',
  path: '/demandes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandesIdRoute = DemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connaissances': typeof ConnaissancesRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/demandes/': typeof DemandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connaissances': typeof ConnaissancesRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/demandes': typeof DemandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connaissances': typeof ConnaissancesRoute
  '/notifications': typeof NotificationsRoute
  '/planning': typeof PlanningRoute
  '/demandes/$id': typeof DemandesIdRoute
  '/demandes/': typeof DemandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connaissances'
    | '/notifications'
    | '/planning'
    | '/demandes/$id'
    | '/demandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connaissances'
    | '/notifications'
    | '/planning'
    | '/demandes/$id'
    | '/demandes'
  id:
    | '__root__'
    | '/'
    | '/connaissances'
    | '/notifications'
    | '/planning'
    | '/demandes/$id'
    | '/demandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnaissancesRoute: typeof ConnaissancesRoute
  NotificationsRoute: typeof NotificationsRoute
  PlanningRoute: typeof PlanningRoute
  DemandesIdRoute: typeof DemandesIdRoute
  DemandesIndexRoute: typeof DemandesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connaissances': {
      id: '/connaissances'
      path: '/connaissances'
      fullPath: '/connaissances'
      preLoaderRoute: typeof ConnaissancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/': {
      id: '/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof DemandesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demandes/$id': {
      id: '/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof DemandesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnaissancesRoute: ConnaissancesRoute,
  NotificationsRoute: NotificationsRoute,
  PlanningRoute: PlanningRoute,
  DemandesIdRoute: DemandesIdRoute,
  DemandesIndexRoute: DemandesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
